name: Goldfish
main: org.nationsatwar.goldfish.Goldfish
version: 1.0

commands:
  instance:
    description: This is a demo command.
    permission: Goldfish.basic
    usage: /<command>
  goldfish:
    description: This is also a demo command.
    permission: Goldfish.basic
    usage: /<command>
    
permissions:
  goldfish.*:
    description: Gives access to all goldfish commands
    children:
      naw.test: true
      naw.test2: false
  instance.*:
    description: Gives access to all goldfish commands
    children:
      naw.test: true
      naw.test2: false